In [1]:
import rasterio
import numpy as np

In [2]:
# Open the GeoTIFF file
file_path = '/Users/nayandas/Downloads/42S_20170101-20180101.tif'

In [3]:
with rasterio.open(file_path) as src:
    # metadata = src.meta
    # print("Metadata:", metadata)

    band1 = src.read(1)  # Replace 1 with the desired band number
    print(band1)
    print(type(band1))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>


In [4]:
band1.shape

(89162, 56684)

In [6]:
band1[0].unique()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'